# Travis-CI Build for log4stash (copied from WampSharp)
# Copied from keyczar-dotnet
# The Elasticsearch install copied from elasticsearch-dsl-py
# see travis-ci.org for details

language: csharp

solution: src/log4stash.sln

env:
 global:
  - EnableNuGetPackageRestore=true
 matrix:
  - ES_VERSION=1.4.4

before_install:
 - mkdir /tmp/elasticsearch
 - wget -O - https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
 - /tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false
#- /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp 

script:
 - xbuild /p:Configuration=Release /p:Travis=True src/log4stash.sln	
 - sh src/.ci/RunTests.sh

branches:
 only:
  - dev
  - master